modLoader = "javafml"
loaderVersion="[1,)"
license="LGPL"
showAsResourcePack=false

[[mods]]
modId="chatshot"
version="${version}"
displayName="ChatShot"
authors="DeDiamondPro"
description="Copy chat messages as text or a nice transparent image with one click."
logoFile="chatshot-128x.png"

[[dependencies.chatshot]]
modId="minecraft"
mandatory=true
versionRange="${mcVersion}"
ordering="NONE"
side="BOTH"

[[dependencies.chatshot]]
modId="yet_another_config_lib_v3"
versionRange="[3.0.0,)"
mandatory=true
side="CLIENT"

[[mixins]]
config = "mixins.chatshot.json"